### ISSUE TITLE
How I can download your paper?

### ISSUE THREAD

**Issue by lxtGH** [jsuarez5341/Recurrent-Highway-Hypernetworks-NIPS#1]
Now I am studying the hyper network, I google your paper but I can't find it

**Comment by jsuarez5341** [comment]
I have no idea how you found this repo already. The paper is not on arxiv; it is appearing in NIPS 2017. If you are only interested in standard hypernetworks and not my variant, the original Hypernetworks paper is probably a better place to start. If you're looking for code examples, try the last few lines of models/HyperRHN.py. Note that in my case, the recurrent cell is a recurrent highway network as opposed to an LSTM.

**Comment by lxtGH** [comment]
I don't understand the code **HyperLinear.py, line 25,26**
I run the Main.py , it give the **NotImplementedError,**  in that file

**Comment by jsuarez5341** [comment]
I just cloned a clean copy and it works fine on my machine. Did you run it from the top level directory? Please post your error trace so I can take a look.

**Comment by lxtGH** [comment]
Sorry for late reply, I run it from the top level directory
/home/lxt/anaconda3/bin/python /home/lxt/pytorch/Recurrent-Highway-Hypernetworks-NIPS/Main.py
Loading Data...
Data Loaded.
Initializing weights. Warning: may overwrite sensitive bias parameters (e.g. batchnorm)
Network has  187 K params
#Traceback (most recent call last):
  File "/home/lxt/pytorch/Recurrent-Highway-Hypernetworks-NIPS/Main.py", line 24, in <module>
    context, minContext, eta, saveName, load)
  File "/home/lxt/pytorch/Recurrent-Highway-Hypernetworks-NIPS/Run.py", line 99, in run
    train(net, opt, trainBatcher, validBatcher, saver, minContext)
  File "/home/lxt/pytorch/Recurrent-Highway-Hypernetworks-NIPS/Run.py", line 63, in train
    trainable=True, verbose=True)
  File "/home/lxt/pytorch/Recurrent-Highway-Hypernetworks-NIPS/utils.py", line 166, in runData
    a, y = runMinibatch(net, batcher, trainable=trainable, cuda=cuda, volatile=not trainable)
  File "/home/lxt/pytorch/Recurrent-Highway-Hypernetworks-NIPS/utils.py", line 106, in runMinibatch
    a = net(x, trainable)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lxt/pytorch/Recurrent-Highway-Hypernetworks-NIPS/Run.py", line 50, in forward
    o, s = self.cell(x[:, i], s, trainable)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lxt/pytorch/Recurrent-Highway-Hypernetworks-NIPS/models/HyperRHN.py", line 50, in forward
    out, sNetwork = self.RHNCell(x, sNetwork, z, trainable)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lxt/pytorch/Recurrent-Highway-Hypernetworks-NIPS/models/HyperRHN.py", line 26, in forward
    Ws = self.cell[l](s[l], z[l])
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lxt/pytorch/Recurrent-Highway-Hypernetworks-NIPS/HyperLinear.py", line 25, in forward
    Wx = self._backend.Linear()(input, weight)*z
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/nn/backends/backend.py", line 10, in __getattr__
    raise NotImplementedError
NotImplementedError

**Comment by jsuarez5341** [comment]
I'm having trouble reproducing this--works out of the box on the same conda/python version for me. The only thing I can think of is the pytorch version? I'm running v0.1.12_2 ... Are you on the same version? Also, I'm currently pushing some major changes and waiting for final correctness checks to finish--I'll be able to check version errors once they finish in a couple days. In the meanwhile, please let me know if you're already on the same pytorch version.

**Comment by lxtGH** [comment]
My torch version is v0.2.0_4 the code can not run in this version. 
However, the code can run on  v0.1.12_2 after I reinstall this version.
So it is a version problem

**Comment by jsuarez5341** [comment]
I see. Please run on the 1.12_2 for now. I plan on migrating all my projects (one is still in development) soon, but I'd like to hold off until all correctness checks are complete.
